---
title: "Q4_Cor_Diseases"
author: "Vedang Sawarkar"
date: "11/12/2021"
output: html_document
---

```{r}
setwd("D:\\SEM 5\\Data Analytics\\J Comp\\COVID-FDA")
df = read.csv("Dataset\\preprocessed_data.csv")
df
```
```{r}
names(df)
```
```{r}
diseases <- df[,c(9,12,13,14,15,16,17,18,19,20)] 
names(diseases)
head(diseases)
```

```{r}
library(tidyr)
```

```{r}
diseases <- drop_na(diseases)
```

```{r}
dim(diseases)
```
```{r}
table(is.na(diseases))
```

```{r}

cor_values <- matrix(nrow=10, ncol=10)
for(i in 1:10){
  for(j in 1:10){
     y = unclass(chisq.test(diseases[,i],diseases[,j]))[3]
    #print(y$p.value)
    cor_values[i,j] = y
    cor_values = matrix(cor_values, nrow=10, ncol=10)
  }
}
```

```{r}
names(diseases)
```


```{r}
rownames(cor_values) <- c("pneumonia", "diabetes", "copd", "asthma", "inmsupr", "hypertension", "other_disease", "cardiovascular", "obesity", "renal_chronic")

colnames(cor_values) <- c("pneumonia", "diabetes", "copd", "asthma", "inmsupr", "hypertension", "other_disease", "cardiovascular", "obesity", "renal_chronic")
cor_values
```











