---
title: "question 9 and 10"
author: "Tejas Vaichole"
---

## QUESTION 9 and 10

```{r}
data9 = data
data9$difference = difftime(data$entry_date,data$date_symptoms,units=c("days"))

boxplot((data9$difference) ~ data9$intubed, xlab="Intubed", ylab="Time taken to admit (in days)")
boxplot((data9$difference) ~ data9$icu, xlab="Admitted in ICU", ylab="Time taken to admit (in days)")
boxplot((data9$difference) ~ data9$mortality, xlab="Mortality", ylab="Time taken to admit (in days)")
```



```{r}
### Removing Outliers 
data9 = data9[data9$difference < 15,]
### Divide the differnce in interval of 5 days 
data9$difference_range = cut(as.numeric(data9$difference), c(0,5,10,15))

grouped_intubed = data9 %>% dplyr::select(difference_range, intubed) %>% na.omit() %>% group_by(difference_range, intubed) %>% summarise(count = n())

grouped_icu = data9 %>% dplyr::select(difference_range, icu) %>% na.omit() %>% group_by(difference_range, icu) %>% summarise(count = n())

grouped_mortality = data9 %>% dplyr::select(difference_range, mortality) %>% na.omit() %>% group_by(difference_range, mortality) %>% summarise(count = n())
```

```{r}
# Stacked barplot with multiple groups
ggplot(data=grouped_intubed, aes(x=difference_range,y=count,fill=intubed)) + geom_bar(stat="identity",position=position_dodge()) + xlab("Interval of time taken to admit (in days)") + ylab("Number of people")


ggplot(data=grouped_icu, aes(x=difference_range,y=count,fill=icu)) + geom_bar(stat="identity",position=position_dodge()) + xlab("Interval of time taken to admit (in days)") + ylab("Number of people")

ggplot(data=grouped_mortality, aes(x=difference_range,y=count,fill=mortality)) + geom_bar(stat="identity",position=position_dodge()) + xlab("Interval of time taken to admit (in days)") + ylab("Number of people")

```


```{r}
grouped_intubed1 = data9 %>% dplyr::select(difference, intubed) %>% filter(intubed=="Yes")  %>% na.omit() %>% group_by(difference) %>% summarise(count = n()) %>% mutate(difference = as.numeric(difference))

grouped_icu1 = data9 %>% dplyr::select(difference, icu) %>% filter(icu=="Yes")  %>% na.omit() %>% group_by(difference) %>% summarise(count = n()) %>% mutate(difference = as.numeric(difference))

grouped_mortality1 = data9 %>% dplyr::select(difference, mortality) %>% filter(mortality=="Died")  %>% na.omit() %>% group_by(difference) %>% summarise(count = n()) %>% mutate(difference = as.numeric(difference))

ggplot(data=grouped_intubed1, aes(x=difference,y=count)) + geom_bar(stat="identity") + xlab("Interval of time taken to admit (in days)") + ylab("Number of people intubed")

ggplot(data=grouped_icu1, aes(x=difference,y=count)) + geom_bar(stat="identity") + xlab("Interval of time taken to admit (in days)") + ylab("Number of people in icu")

ggplot(data=grouped_mortality1, aes(x=difference,y=count)) + geom_bar(stat="identity") + xlab("Interval of time taken to admit (in days)") + ylab("Number of people died")
```